src/Dotnet6.GraphQL4.Store.WebMVC/Models/AddedReviewSubscriptionResult.cs
namespace Dotnet6.GraphQL4.Store.WebMVC.Models;

public class AddedReviewSubscriptionResult
{
    public ReviewModel Review { get; set; }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Models/ErrorViewModel.cs
using System.Collections.Generic;

namespace Dotnet6.GraphQL4.Store.WebMVC.Models;

public class ErrorViewModel
{
    public List<string> Erros { get; set; }
    public string RequestId { get; init; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Dotnet6.GraphQL4.Store.WebMVC/Models/ProductModel.cs
using System;
using System.Collections.Generic;

namespace Dotnet6.GraphQL4.Store.WebMVC.Models;

public class ProductModel
{
    public string Description { get; set; }
    public Guid Id { get; set; }
    public DateTimeOffset IntroduceAt { get; set; }
    public string Name { get; set; }
    public string PhotoUrl { get; set; }
    public decimal Price { get; set; }
    public int Rating { get; set; }
    public int Stock { get; set; }
    public IEnumerable<ReviewModel> Reviews { get; set; }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Models/ReviewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Dotnet6.GraphQL4.Store.WebMVC.Models;

public class ReviewModel
{
    [Required, StringLength(400)]
    public string Comment { get; init; }
        
    [Required, StringLength(100)]
    public string Title { get; init; }
        
    [Required]
    public Guid ProductId { get; init; }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Dotnet6.GraphQL4.Store.WebMVC.Clients;
using Dotnet6.GraphQL4.Store.WebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Dotnet6.GraphQL4.Store.WebMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IStoreGraphClient _storeGraphClient;

    public HomeController(ILogger<HomeController> logger, IStoreGraphClient storeGraphClient)
    {
        _logger = logger;
        _storeGraphClient = storeGraphClient;
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
        => View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});

    public async Task<IActionResult> Index()
    {
        var response = await _storeGraphClient
            .GetAllProductsAsync();

        return View(response);
    }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Controllers/ProductsController.cs
using System;
using System.Threading.Tasks;
using Dotnet6.GraphQL4.Store.WebMVC.Clients;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Dotnet6.GraphQL4.Store.WebMVC.Controllers;

public class ProductsController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IStoreGraphClient _storeGraphClient;

    public ProductsController(ILogger<HomeController> logger, IStoreGraphClient storeGraphClient)
    {
        _logger = logger;
        _storeGraphClient = storeGraphClient;
    }

    public async Task<IActionResult> Detail(Guid id)
    {
        _storeGraphClient.SubscribeToUpdates();
        var product = await _storeGraphClient.GetProductByIdAsync(id);
        return View(product);
    }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Controllers/ReviewsController.cs
using System;
using System.Threading.Tasks;
using Dotnet6.GraphQL4.Store.WebMVC.Clients;
using Dotnet6.GraphQL4.Store.WebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Dotnet6.GraphQL4.Store.WebMVC.Controllers;

public class ReviewsController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IStoreGraphClient _storeGraphClient;

    public ReviewsController(ILogger<HomeController> logger, IStoreGraphClient storeGraphClient)
    {
        _logger = logger;
        _storeGraphClient = storeGraphClient;
    }

    public async Task<IActionResult> Reviews(Guid id)
    {
        var reviews = await _storeGraphClient
            .GetReviewByProductIdAsync(id);

        return View(reviews);
    }

    public IActionResult Add(Guid productId)
        => View(new ReviewModel {ProductId = productId});

    [HttpPost]
    public async Task<IActionResult> Add(ReviewModel model)
    {
        if (ModelState.IsValid)
            await _storeGraphClient.AddReviewAsync(model);

        return RedirectToAction(
            actionName: "Detail",
            controllerName: "Products",
            routeValues: new {id = model.ProductId});
    }
}

src/Dotnet6.GraphQL4.Store.WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Store";
}

<body>
<div class="product-list">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Products</h2>
            <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
        </div>
        <div class="row products">
            @foreach (var product in Model)
            {
                <div class="col-sm-6 col-md-4 item">
                    <a asp-controller="Products" asp-action="Detail" asp-route-id="@product.Id">
                        <img class="img-fluid" src="@product.PhotoUrl" alt="">
                    </a>
                    <h3 class="name">@product.Name</h3>
                    <p class="description">@product.Description</p>
                    <a class="action" asp-controller="Products" asp-action="Detail" asp-route-id="@product.Id">
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            }
        </div>
    </div>
</div>
</body>

src/Dotnet6.GraphQL4.Store.WebMVC/Views/Products/Detail.cshtml
@using Dotnet6.GraphQL4.Store.WebMVC.Models
@{
    ViewData["Title"] = "Product Detail";
    IEnumerable<ReviewModel> reviews = Model.Reviews;
}

<body>
<div class="product-list"></div>
<div class="product-dual-column">
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1 text-center">
                <div class="intro">
                    <h1 class="text-center">@Model.Name</h1>
                    <img class="img-fluid" src="@Model.PhotoUrl" alt="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-lg-3 offset-md-1">
                <div class="details">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Price: @Model.Price </li>
                        <li class="list-group-item">Rating: @Model.Rating</li>
                        <li class="list-group-item">Introduce at: @Model.IntroduceAt.ToString("dd/MM/yyyy") </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                <div class="text">
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-12 col-md-7">
            @if (reviews is null || reviews.Any() is false)
            {
                <div class="row justify-content-center text-center" style="margin-top: 2%; padding: 1%">
                    <a asp-controller="Reviews" asp-action="Add" asp-route-productId="@Model.Id" class="btn btn-outline-secondary">Add first review</a>
                </div>
            }
            else
            {
                @foreach (var review in Model.Reviews)
                {
                    <div class="list-group ">
                        <a href="#" class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">@review.Title</h5>
                                <small>3 days ago</small>
                            </div>
                            <p class="mb-1">@review.Comment</p>
                            <small>Donec id elit non mi porta.</small>
                        </a>
                    </div>
                }
                <div class="row justify-content-center text-center" style="margin-top: 2%; padding: 1%">
                    <a asp-controller="Reviews" asp-action="Reviews" asp-route-id="@Model.Id" class="btn btn-outline-secondary review-btn">See all</a>
                    <a asp-controller="Reviews" asp-action="Add" asp-route-productId="@Model.Id" class="btn btn-outline-secondary review-btn">Add a review</a>
                </div>
            }
        </div>
    </div>
</div>
</body>

src/Dotnet6.GraphQL4.Store.WebMVC/Views/Reviews/Add.cshtml
@{
    ViewBag.Title = "Add Review";
    var productId = Model.ProductId;
}
<body>
<div class="col-12 col-md-8">
    <form method="post" asp-controller="Reviews" asp-action="Add">
        <div class="form-group">
            <label for="Title">Title</label>
            <input class="form-control form-control-lg" type="text" name="Title" id="Title" placeholder="Title" required>
            <small id="emailHelp" class="form-text text-muted">Use a title that refers to the subject.</small>
        </div>
        <div class="form-group">
            <label for="Review">Review</label>
            <textarea class="form-control" name="Comment" id="Review" placeholder="Comment" rows="5" required></textarea>
        </div>
        <input name="ProductId" type="hidden" value="@productId">
        <button type="submit" class="btn btn-outline-secondary">Add a review</button>
    </form>
</div>
</body>

src/Dotnet6.GraphQL4.Store.WebMVC/Views/Reviews/Reviews.cshtml
@using Dotnet6.GraphQL4.Store.WebMVC.Models
@{
    ViewData["Title"] = "Product Review";
    IEnumerable<ReviewModel> reviews = Model;
    var productId = reviews?.FirstOrDefault()?.ProductId;
}

<h3 class="text-center">Reviews</h3>

<body>

@if (reviews is null || reviews.Any() is false)
{
    <h5>No reviews yet</h5>
}
else
{
    @foreach (var review in reviews)
    {
        <div class="row">
            <ul class="list-group list-group-flush">
                <li class="list-group-item" style="font-size: x-large">@review.Title</li>
                <li class="list-group-item" style="font-size: small">@review.Comment</li>
            </ul>
        </div>
    }

    <a asp-controller="Reviews" asp-action="Add" asp-route-productId="@productId" class="btn btn-outline-secondary review-btn">Add a review</a>
}

</body>

src/Dotnet6.GraphQL4.Store.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/Article-Dual-Column.css"/>
    <link rel="stylesheet" href="~/css/Article-List.css"/>
    <link rel="stylesheet" href="~/css/Styles.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store</a>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Store
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>